services:
  - type: web
    name: gym-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python railway_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false 